# Generated by Django 5.1.7 on 2025-03-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='newsletter_text',
        ),
    ]
