# Generated by Django 5.1.7 on 2025-03-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_siteinfo_newsletter_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='twitter_link',
        ),
    ]
