# Generated by Django 5.1.7 on 2025-03-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='address',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='location',
            field=models.CharField(default='14 Fətəli Xan Xoyski, Bakı', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(default='multishop@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(default='+994 51 651 09 99', max_length=20),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
