# Generated by Django 5.1.7 on 2025-03-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cartitem_product_delete_sitesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(default='+994 51 651 09 09', max_length=20),
        ),
    ]
