# Generated by Django 5.1.7 on 2025-03-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_siteinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
