# Generated by Django 5.1.7 on 2025-03-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_billingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Big_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='slider_news/')),
                ('slider_title', models.CharField(max_length=100)),
                ('slider_content', models.TextField(default='Default content')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Small_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='small_slider_news/')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='Default content')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
        migrations.RenameField(
            model_name='useremail',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
