# Generated by Django 5.1.7 on 2025-03-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_big_slider_small_slider_delete_billingaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Big_slider2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image2', models.ImageField(upload_to='slider_news/')),
                ('slider_title2', models.CharField(max_length=100)),
                ('slider_content2', models.TextField(default='Default content')),
                ('created_date2', models.DateTimeField(auto_now_add=True)),
                ('is_activate2', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Big_slider3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image3', models.ImageField(upload_to='slider_news/')),
                ('slider_title3', models.CharField(max_length=100)),
                ('slider_content3', models.TextField(default='Default content')),
                ('created_date3', models.DateTimeField(auto_now_add=True)),
                ('is_activate3', models.BooleanField(default=True)),
            ],
        ),
    ]
