# Generated by Django 5.1.7 on 2025-03-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_big_slider2_big_slider3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Big_slider2',
        ),
        migrations.DeleteModel(
            name='Big_slider3',
        ),
        migrations.AlterField(
            model_name='big_slider',
            name='slider_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='small_slider',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
