# Generated by Django 5.1.7 on 2025-03-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='message',
        ),
    ]
