# Generated by Django 5.1.7 on 2025-03-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product2nd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='tiktok',
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='instagram',
            field=models.URLField(default='https://instagram.com/'),
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='twitter',
            field=models.URLField(default='https://twitter.com/'),
        ),
        migrations.AlterField(
            model_name='product2nd',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
