# Generated by Django 5.1.7 on 2025-04-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_sociallinks_tiktok_sociallinks_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product2nd',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
