# Generated by Django 5.1.7 on 2025-04-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product_is_active_product2nd_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2nd',
        ),
    ]
